packages:
  - playground
  - docs
  - packages/*
  - examples/*

ignoreWorkspaceRootCheck: true
shellEmulator: true

catalogs:
  build:
    tsdown: ^0.16.0
    typescript: ^5.9.3
    vite: ^7.2.1
  inlined:
    '@antfu/utils': ^9.3.0
  lint:
    '@antfu/eslint-config': ^6.2.0
    eslint: ^9.39.1
  prod:
    '@google/generative-ai': ^0.24.1
    inquirer: ^9.2.20
    inquirer-autocomplete-prompt: ^3.0.1
    inquirer-search-checkbox: ^1.0.0
    is-ip: ^5.0.1
    kolorist: ^1.8.0
    open: ^8.4.2
    ora: ^9.0.0
    yargs: ^17.7.2
  script:
    '@antfu/ni': ^27.0.1
    bumpp: ^10.3.1
    lint-staged: ^16.2.6
    simple-git-hooks: ^2.13.1
    tinyexec: ^1.0.2
    tsx: ^4.20.6
  test:
    vitest: ^4.0.7
    vitest-package-exports: ^0.1.1
    yaml: ^2.8.1
  types:
    '@types/inquirer': ^9.0.7
    '@types/inquirer-autocomplete-prompt': ^3.0.3
    '@types/node': ^24.10.0
    '@types/yargs': ^17.0.32
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
